# Generated by Django 4.2.14 on 2024-08-06 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="room",
            name="room_pic",
            field=models.ImageField(default=False, upload_to="img/room"),
        ),
    ]
