# Generated by Django 4.2.14 on 2024-08-06 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("homeapp", "0002_room_room_pic"),
    ]

    operations = [
        migrations.AddField(
            model_name="booking",
            name="price",
            field=models.DecimalField(decimal_places=2, default=True, max_digits=10),
        ),
        migrations.AlterField(
            model_name="room",
            name="room_pic",
            field=models.ImageField(blank=True, null=True, upload_to="rooms/"),
        ),
    ]
