# Generated by Django 4.2.14 on 2024-08-08 16:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("homeapp", "0003_booking_price_alter_room_room_pic"),
    ]

    operations = [
        migrations.RemoveField(model_name="payment", name="hostel_name",),
        migrations.RemoveField(model_name="payment", name="room",),
        migrations.RemoveField(model_name="payment", name="session",),
        migrations.AlterField(
            model_name="payment",
            name="room_type",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="homeapp.room",
            ),
        ),
    ]
